services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: alem_backend
    environment:

    env_file:
      - ./backend/auth/.env
    ports:
      - "8001:8000"
    volumes:
      - ./backend/auth:/service

    networks:
      - auth-network
    restart: on-failure

